CREATE TABLE IF NOT EXISTS moto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa         VARCHAR(10),
    modelo        VARCHAR(50),
    numero_chassi VARCHAR(17),
    status        VARCHAR(255)                            NOT NULL,
    patio_id      BIGINT,
    CONSTRAINT pk_moto PRIMARY KEY (id),
    CONSTRAINT uc_moto_placa UNIQUE (placa),
    CONSTRAINT uc_moto_chassi UNIQUE (numero_chassi)
);