CREATE TABLE IF NOT EXISTS patio
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(100),
    endereco VARCHAR(255),
    CONSTRAINT pk_patio PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sensor_localizacao
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude            DOUBLE PRECISION NOT NULL,
    longitude           DOUBLE PRECISION NOT NULL,
    time_da_localizacao TIMESTAMP        NOT NULL,
    moto_id             BIGINT           NOT NULL,
    CONSTRAINT pk_sensor_localizacao PRIMARY KEY (id)

);